name: inventory-utt
services:
  db:
    container_name: mysql
    env_file: .env
    build:
      context: ./ 
      dockerfile: ./Dockerfile
    ports:
      - 3306:3306
    networks:
      - utt-network
    volumes:
      - ./mysql_data:/var/lib/mysql
  api:
    container_name: net-api
    env_file: .env
    environment:
      - DB_CONNECTION=server=mysql;uid=root;pwd=${MYSQL_ROOT_PASSWORD};database=INVENTORY_UTT
    build: 
      context: ./
      dockerfile: ./Dockerfile.API
      args:
        - DB_CONNECTION=server=mysql;uid=root;pwd=${MYSQL_ROOT_PASSWORD};database=INVENTORY_UTT
        - API_KEY=${API_KEY}
    ports: 
      - 8080:80
    networks:
      - utt-network
    depends_on:
      - db
  react-app:
    container_name: react-app
    env_file: .env
    build:
      context: ./
      dockerfile: ./Dockerfile.client
    # volumes:
    #   - ./front-end/src:/usr/src/app/src
    #   # - /project/node_modules
    ports:
      - 3000:3000
    networks:
      - utt-network
    depends_on:
      - api
    restart: on-failure
networks:
  utt-network:
    driver: bridge
