FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app
COPY ./src ./

# Building binaries
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /bin
COPY --from=build /src/app .
ENTRYPOINT [ "dotnet", "InventoryAPI.dll" ]